// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEmNaKnbDbt6GnOHEL9Wizu_7fzb7Lifw',
    appId: '1:481248549086:web:87e1b1d37a5eb454a8ca4f',
    messagingSenderId: '481248549086',
    projectId: 'login-signup-firebase-88377',
    authDomain: 'login-signup-firebase-88377.firebaseapp.com',
    databaseURL: 'https://login-signup-firebase-88377-default-rtdb.firebaseio.com',
    storageBucket: 'login-signup-firebase-88377.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0OKHwlLT75OGNDVlkHcUbXgfjkoUaiDQ',
    appId: '1:481248549086:android:105bed0bf31ab0c8a8ca4f',
    messagingSenderId: '481248549086',
    projectId: 'login-signup-firebase-88377',
    databaseURL: 'https://login-signup-firebase-88377-default-rtdb.firebaseio.com',
    storageBucket: 'login-signup-firebase-88377.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd9nZ0SIp_VawolfFmsZYCyiUeWwqLS-Y',
    appId: '1:481248549086:ios:a5634d5549195291a8ca4f',
    messagingSenderId: '481248549086',
    projectId: 'login-signup-firebase-88377',
    databaseURL: 'https://login-signup-firebase-88377-default-rtdb.firebaseio.com',
    storageBucket: 'login-signup-firebase-88377.appspot.com',
    iosBundleId: 'com.example.commonFeatures',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd9nZ0SIp_VawolfFmsZYCyiUeWwqLS-Y',
    appId: '1:481248549086:ios:a5634d5549195291a8ca4f',
    messagingSenderId: '481248549086',
    projectId: 'login-signup-firebase-88377',
    databaseURL: 'https://login-signup-firebase-88377-default-rtdb.firebaseio.com',
    storageBucket: 'login-signup-firebase-88377.appspot.com',
    iosBundleId: 'com.example.commonFeatures',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEmNaKnbDbt6GnOHEL9Wizu_7fzb7Lifw',
    appId: '1:481248549086:web:ed240fd8b0b8c0caa8ca4f',
    messagingSenderId: '481248549086',
    projectId: 'login-signup-firebase-88377',
    authDomain: 'login-signup-firebase-88377.firebaseapp.com',
    databaseURL: 'https://login-signup-firebase-88377-default-rtdb.firebaseio.com',
    storageBucket: 'login-signup-firebase-88377.appspot.com',
  );
}
